export type ExerciseLoadType = 'weighted' | 'bodyweight' | 'assisted' | 'cardio' | 'duration';
export type ExerciseCategory = 'chest' | 'back' | 'legs_glutes' | 'shoulders' | 'arms' | 'core' | 'cardio' | 'full_body';
export type ExercisePattern =
  | 'horizontal_push'
  | 'vertical_push'
  | 'horizontal_pull'
  | 'vertical_pull'
  | 'squat'
  | 'hinge'
  | 'lunge'
  | 'isolation'
  | 'core_flexion'
  | 'core_anti_extension'
  | 'cardio'
  | 'carry'
  | 'mixed';

export type ExerciseUnit = 'kg' | 'bodyweight' | 'min' | 'km';
export type ExerciseField = 'weight' | 'reps' | 'sets' | 'duration' | 'distance';
export type ExerciseOptionalField = 'note' | 'rpe' | 'heartRate' | 'calories' | 'distance';

export type ExerciseDefinition = {
  id: string;
  canonicalName: string;
  displayName: string;
  category: ExerciseCategory;
  primaryMuscles: string[];
  secondaryMuscles?: string[];
  equipment: string[];
  pattern: ExercisePattern;
  loadType: ExerciseLoadType;
  aliases: string[];
  defaultUnit: ExerciseUnit;
  requiredFields: ExerciseField[];
  optionalFields?: ExerciseOptionalField[];
  isUnilateralCommon?: boolean;
  notes?: string;
};

export const exerciseLibrary = [
  {
    id: 'barbell_bench_press',
    canonicalName: '杠铃卧推',
    displayName: '杠铃卧推',
    category: 'chest',
    primaryMuscles: ['胸大肌'],
    secondaryMuscles: ['肱三头肌', '三角肌前束'],
    equipment: ['杠铃', '卧推凳'],
    pattern: 'horizontal_push',
    loadType: 'weighted',
    aliases: ['平板杠铃卧推', '杠铃卧推', '平板卧推', '卧推', 'bench press', 'barbell bench press'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'dumbbell_bench_press',
    canonicalName: '哑铃卧推',
    displayName: '哑铃卧推',
    category: 'chest',
    primaryMuscles: ['胸大肌'],
    secondaryMuscles: ['肱三头肌', '三角肌前束'],
    equipment: ['哑铃', '卧推凳'],
    pattern: 'horizontal_push',
    loadType: 'weighted',
    aliases: ['平板哑铃卧推', '哑铃卧推', 'dumbbell bench press', 'db bench press'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    isUnilateralCommon: true,
    notes: '重量通常按单只哑铃记录。',
  },
  {
    id: 'incline_barbell_bench_press',
    canonicalName: '上斜杠铃卧推',
    displayName: '上斜杠铃卧推',
    category: 'chest',
    primaryMuscles: ['胸大肌上束'],
    secondaryMuscles: ['肱三头肌', '三角肌前束'],
    equipment: ['杠铃', '上斜凳'],
    pattern: 'horizontal_push',
    loadType: 'weighted',
    aliases: ['上斜杠铃卧推', '上斜卧推', 'incline bench press', 'incline barbell bench'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'incline_dumbbell_bench_press',
    canonicalName: '上斜哑铃卧推',
    displayName: '上斜哑铃卧推',
    category: 'chest',
    primaryMuscles: ['胸大肌上束'],
    secondaryMuscles: ['肱三头肌', '三角肌前束'],
    equipment: ['哑铃', '上斜凳'],
    pattern: 'horizontal_push',
    loadType: 'weighted',
    aliases: ['上斜哑铃卧推', '上斜哑铃推', 'incline dumbbell press', 'incline db press'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    isUnilateralCommon: true,
    notes: '重量通常按单只哑铃记录。',
  },
  {
    id: 'machine_chest_press',
    canonicalName: '坐姿推胸',
    displayName: '坐姿推胸',
    category: 'chest',
    primaryMuscles: ['胸大肌'],
    secondaryMuscles: ['肱三头肌', '三角肌前束'],
    equipment: ['推胸机'],
    pattern: 'horizontal_push',
    loadType: 'weighted',
    aliases: ['坐姿推胸', '器械推胸', '推胸机', 'chest press', 'machine chest press'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'pec_deck_fly',
    canonicalName: '蝴蝶机夹胸',
    displayName: '蝴蝶机夹胸',
    category: 'chest',
    primaryMuscles: ['胸大肌'],
    secondaryMuscles: ['三角肌前束'],
    equipment: ['蝴蝶机'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['蝴蝶机夹胸', '夹胸机', '器械夹胸', 'pec deck', 'pec deck fly'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'cable_fly',
    canonicalName: '龙门架夹胸',
    displayName: '龙门架夹胸',
    category: 'chest',
    primaryMuscles: ['胸大肌'],
    secondaryMuscles: ['三角肌前束'],
    equipment: ['龙门架', '绳索'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['龙门架夹胸', '绳索夹胸', '绳索飞鸟', 'cable fly', 'cable crossover'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    isUnilateralCommon: true,
    notes: '重量可能按单边或双边合计记录，后续 UI 可补备注提示。',
  },
  {
    id: 'push_up',
    canonicalName: '俯卧撑',
    displayName: '俯卧撑',
    category: 'chest',
    primaryMuscles: ['胸大肌'],
    secondaryMuscles: ['肱三头肌', '核心'],
    equipment: ['自重'],
    pattern: 'horizontal_push',
    loadType: 'bodyweight',
    aliases: ['俯卧撑', '伏地挺身', 'push up', 'push-up'],
    defaultUnit: 'bodyweight',
    requiredFields: ['reps', 'sets'],
  },
  {
    id: 'pull_up',
    canonicalName: '引体向上',
    displayName: '引体向上',
    category: 'back',
    primaryMuscles: ['背阔肌'],
    secondaryMuscles: ['肱二头肌', '核心'],
    equipment: ['单杠', '自重'],
    pattern: 'vertical_pull',
    loadType: 'bodyweight',
    aliases: ['引体向上', '正手引体', 'pull up', 'pull-up'],
    defaultUnit: 'bodyweight',
    requiredFields: ['reps', 'sets'],
  },
  {
    id: 'assisted_pull_up',
    canonicalName: '辅助引体向上',
    displayName: '辅助引体向上',
    category: 'back',
    primaryMuscles: ['背阔肌'],
    secondaryMuscles: ['肱二头肌'],
    equipment: ['辅助引体机'],
    pattern: 'vertical_pull',
    loadType: 'assisted',
    aliases: ['辅助引体向上', '辅助引体', '助力引体', 'assisted pull up'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    notes: 'weight 表示辅助重量。',
  },
  {
    id: 'lat_pulldown',
    canonicalName: '高位下拉',
    displayName: '高位下拉',
    category: 'back',
    primaryMuscles: ['背阔肌'],
    secondaryMuscles: ['肱二头肌', '斜方肌下束'],
    equipment: ['高位下拉器械', '绳索'],
    pattern: 'vertical_pull',
    loadType: 'weighted',
    aliases: ['高位下拉', '宽握下拉', '下拉', 'lat pulldown', 'pulldown'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'seated_cable_row',
    canonicalName: '坐姿绳索划船',
    displayName: '坐姿绳索划船',
    category: 'back',
    primaryMuscles: ['背阔肌', '菱形肌'],
    secondaryMuscles: ['肱二头肌', '斜方肌'],
    equipment: ['坐姿划船机', '绳索'],
    pattern: 'horizontal_pull',
    loadType: 'weighted',
    aliases: ['坐姿绳索划船', '坐姿划船', '绳索划船', '水平绳索划船', 'seated row', 'cable row'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'barbell_row',
    canonicalName: '杠铃划船',
    displayName: '杠铃划船',
    category: 'back',
    primaryMuscles: ['背阔肌', '菱形肌'],
    secondaryMuscles: ['竖脊肌', '肱二头肌'],
    equipment: ['杠铃'],
    pattern: 'horizontal_pull',
    loadType: 'weighted',
    aliases: ['俯身杠铃划船', '杠铃划船', 'barbell row', 'bent over row'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'dumbbell_row',
    canonicalName: '单臂哑铃划船',
    displayName: '单臂哑铃划船',
    category: 'back',
    primaryMuscles: ['背阔肌', '菱形肌'],
    secondaryMuscles: ['肱二头肌'],
    equipment: ['哑铃'],
    pattern: 'horizontal_pull',
    loadType: 'weighted',
    aliases: ['单臂哑铃划船', '哑铃划船', 'one arm dumbbell row', 'db row'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    isUnilateralCommon: true,
  },
  {
    id: 't_bar_row',
    canonicalName: 'T杠划船',
    displayName: 'T杠划船',
    category: 'back',
    primaryMuscles: ['背阔肌', '菱形肌'],
    secondaryMuscles: ['肱二头肌', '斜方肌'],
    equipment: ['T杠划船机', '杠铃'],
    pattern: 'horizontal_pull',
    loadType: 'weighted',
    aliases: ['T杠划船', 't杠划船', 'T-bar row', 't bar row'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'straight_arm_pulldown',
    canonicalName: '直臂下压',
    displayName: '直臂下压',
    category: 'back',
    primaryMuscles: ['背阔肌'],
    secondaryMuscles: ['三角肌后束'],
    equipment: ['绳索', '龙门架'],
    pattern: 'vertical_pull',
    loadType: 'weighted',
    aliases: ['绳索直臂下压', '直臂下压', '直臂下拉', 'straight arm pulldown'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'barbell_back_squat',
    canonicalName: '杠铃深蹲',
    displayName: '杠铃深蹲',
    category: 'legs_glutes',
    primaryMuscles: ['股四头肌', '臀大肌'],
    secondaryMuscles: ['腘绳肌', '核心'],
    equipment: ['杠铃', '深蹲架'],
    pattern: 'squat',
    loadType: 'weighted',
    aliases: ['杠铃深蹲', '自由深蹲', '深蹲', 'back squat', 'squat'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'front_squat',
    canonicalName: '前蹲',
    displayName: '前蹲',
    category: 'legs_glutes',
    primaryMuscles: ['股四头肌'],
    secondaryMuscles: ['臀大肌', '核心'],
    equipment: ['杠铃'],
    pattern: 'squat',
    loadType: 'weighted',
    aliases: ['杠铃前蹲', '前蹲', 'front squat'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'hack_squat',
    canonicalName: '哈克深蹲',
    displayName: '哈克深蹲',
    category: 'legs_glutes',
    primaryMuscles: ['股四头肌', '臀大肌'],
    secondaryMuscles: ['腘绳肌'],
    equipment: ['哈克深蹲机'],
    pattern: 'squat',
    loadType: 'weighted',
    aliases: ['哈克深蹲', '哈克蹲', 'hack squat'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'leg_press',
    canonicalName: '腿举',
    displayName: '腿举',
    category: 'legs_glutes',
    primaryMuscles: ['股四头肌', '臀大肌'],
    secondaryMuscles: ['腘绳肌'],
    equipment: ['腿举机'],
    pattern: 'squat',
    loadType: 'weighted',
    aliases: ['腿举', '倒蹬', '腿推', 'leg press'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'conventional_deadlift',
    canonicalName: '传统硬拉',
    displayName: '传统硬拉',
    category: 'legs_glutes',
    primaryMuscles: ['臀大肌', '腘绳肌', '竖脊肌'],
    secondaryMuscles: ['背阔肌', '斜方肌'],
    equipment: ['杠铃'],
    pattern: 'hinge',
    loadType: 'weighted',
    aliases: ['传统硬拉', '杠铃硬拉', '硬拉', 'deadlift', 'conventional deadlift'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'romanian_deadlift',
    canonicalName: '罗马尼亚硬拉',
    displayName: '罗马尼亚硬拉',
    category: 'legs_glutes',
    primaryMuscles: ['腘绳肌', '臀大肌'],
    secondaryMuscles: ['竖脊肌'],
    equipment: ['杠铃', '哑铃'],
    pattern: 'hinge',
    loadType: 'weighted',
    aliases: ['罗马尼亚硬拉', '直腿硬拉', 'RDL', 'rdl', 'romanian deadlift'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'hip_thrust',
    canonicalName: '臀桥',
    displayName: '臀桥',
    category: 'legs_glutes',
    primaryMuscles: ['臀大肌'],
    secondaryMuscles: ['腘绳肌', '核心'],
    equipment: ['杠铃', '史密斯机', '自重'],
    pattern: 'hinge',
    loadType: 'weighted',
    aliases: ['杠铃臀桥', '臀桥', '臀推', 'hip thrust', 'glute bridge'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'leg_extension',
    canonicalName: '腿屈伸',
    displayName: '腿屈伸',
    category: 'legs_glutes',
    primaryMuscles: ['股四头肌'],
    equipment: ['腿屈伸机'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['腿屈伸', '腿伸展', 'leg extension'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'leg_curl',
    canonicalName: '腿弯举',
    displayName: '腿弯举',
    category: 'legs_glutes',
    primaryMuscles: ['腘绳肌'],
    equipment: ['腿弯举机'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['俯卧腿弯举', '坐姿腿弯举', '腿后弯举', '腿弯举', 'leg curl'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'hip_adduction',
    canonicalName: '夹腿内收',
    displayName: '夹腿内收',
    category: 'legs_glutes',
    primaryMuscles: ['大腿内收肌群'],
    equipment: ['夹腿机'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['夹腿内收', '腿内收', '髋内收', 'hip adduction', 'adductor machine'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'hip_abduction',
    canonicalName: '髋外展',
    displayName: '髋外展',
    category: 'legs_glutes',
    primaryMuscles: ['臀中肌', '臀小肌'],
    equipment: ['髋外展机'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['髋外展', '腿外展', 'hip abduction', 'abductor machine'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'lunge',
    canonicalName: '箭步蹲',
    displayName: '箭步蹲',
    category: 'legs_glutes',
    primaryMuscles: ['股四头肌', '臀大肌'],
    secondaryMuscles: ['腘绳肌', '核心'],
    equipment: ['自重', '哑铃', '杠铃'],
    pattern: 'lunge',
    loadType: 'weighted',
    aliases: ['行走箭步蹲', '箭步蹲', '弓步蹲', 'lunge', 'walking lunge'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    isUnilateralCommon: true,
  },
  {
    id: 'dumbbell_shoulder_press',
    canonicalName: '哑铃肩推',
    displayName: '哑铃肩推',
    category: 'shoulders',
    primaryMuscles: ['三角肌前束', '三角肌中束'],
    secondaryMuscles: ['肱三头肌'],
    equipment: ['哑铃'],
    pattern: 'vertical_push',
    loadType: 'weighted',
    aliases: ['坐姿哑铃肩推', '哑铃肩推', '肩推', 'dumbbell shoulder press', 'db shoulder press'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    isUnilateralCommon: true,
    notes: '重量通常按单只哑铃记录。',
  },
  {
    id: 'barbell_overhead_press',
    canonicalName: '杠铃推举',
    displayName: '杠铃推举',
    category: 'shoulders',
    primaryMuscles: ['三角肌前束', '三角肌中束'],
    secondaryMuscles: ['肱三头肌', '核心'],
    equipment: ['杠铃'],
    pattern: 'vertical_push',
    loadType: 'weighted',
    aliases: ['杠铃推举', '杠铃肩推', '推举', 'overhead press', 'barbell overhead press', 'OHP', 'ohp'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'smith_machine_shoulder_press',
    canonicalName: '史密斯肩推',
    displayName: '史密斯肩推',
    category: 'shoulders',
    primaryMuscles: ['三角肌前束', '三角肌中束'],
    secondaryMuscles: ['肱三头肌'],
    equipment: ['史密斯机'],
    pattern: 'vertical_push',
    loadType: 'weighted',
    aliases: ['史密斯肩推', '史密斯推举', 'smith shoulder press'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'dumbbell_lateral_raise',
    canonicalName: '哑铃侧平举',
    displayName: '哑铃侧平举',
    category: 'shoulders',
    primaryMuscles: ['三角肌中束'],
    equipment: ['哑铃'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['哑铃侧平举', '侧平举', 'dumbbell lateral raise', 'lateral raise'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    isUnilateralCommon: true,
    notes: '重量通常按单只哑铃记录。',
  },
  {
    id: 'cable_lateral_raise',
    canonicalName: '绳索侧平举',
    displayName: '绳索侧平举',
    category: 'shoulders',
    primaryMuscles: ['三角肌中束'],
    equipment: ['绳索', '龙门架'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['龙门架侧平举', '绳索侧平举', 'cable lateral raise'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    isUnilateralCommon: true,
  },
  {
    id: 'rear_delt_fly',
    canonicalName: '俯身飞鸟',
    displayName: '俯身飞鸟',
    category: 'shoulders',
    primaryMuscles: ['三角肌后束'],
    secondaryMuscles: ['菱形肌'],
    equipment: ['哑铃', '器械'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['俯身飞鸟', '反向飞鸟', '后束飞鸟', 'rear delt fly', 'reverse fly'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    isUnilateralCommon: true,
  },
  {
    id: 'face_pull',
    canonicalName: '面拉',
    displayName: '面拉',
    category: 'shoulders',
    primaryMuscles: ['三角肌后束', '肩袖肌群'],
    secondaryMuscles: ['斜方肌中下束'],
    equipment: ['绳索'],
    pattern: 'horizontal_pull',
    loadType: 'weighted',
    aliases: ['绳索面拉', '面拉', 'face pull'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'shrug',
    canonicalName: '耸肩',
    displayName: '耸肩',
    category: 'shoulders',
    primaryMuscles: ['斜方肌上束'],
    equipment: ['哑铃', '杠铃', '史密斯机'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['哑铃耸肩', '杠铃耸肩', '耸肩', 'shrug'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    isUnilateralCommon: true,
  },
  {
    id: 'dumbbell_curl',
    canonicalName: '哑铃弯举',
    displayName: '哑铃弯举',
    category: 'arms',
    primaryMuscles: ['肱二头肌'],
    secondaryMuscles: ['肱肌'],
    equipment: ['哑铃'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['哑铃弯举', '二头弯举', '弯举', 'dumbbell curl', 'db curl'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    isUnilateralCommon: true,
  },
  {
    id: 'barbell_curl',
    canonicalName: '杠铃弯举',
    displayName: '杠铃弯举',
    category: 'arms',
    primaryMuscles: ['肱二头肌'],
    secondaryMuscles: ['肱肌'],
    equipment: ['杠铃', 'EZ杠'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['杠铃弯举', 'EZ杠弯举', 'ez curl', 'barbell curl'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'hammer_curl',
    canonicalName: '锤式弯举',
    displayName: '锤式弯举',
    category: 'arms',
    primaryMuscles: ['肱肌', '肱桡肌'],
    secondaryMuscles: ['肱二头肌'],
    equipment: ['哑铃'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['锤式弯举', '锤举', 'hammer curl'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
    isUnilateralCommon: true,
  },
  {
    id: 'triceps_pushdown',
    canonicalName: '绳索下压',
    displayName: '绳索下压',
    category: 'arms',
    primaryMuscles: ['肱三头肌'],
    equipment: ['绳索', '龙门架'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['三头绳索下压', '绳索下压', '三头下压', 'triceps pushdown', 'cable pushdown'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'overhead_triceps_extension',
    canonicalName: '颈后三头臂屈伸',
    displayName: '颈后三头臂屈伸',
    category: 'arms',
    primaryMuscles: ['肱三头肌'],
    equipment: ['哑铃', '绳索'],
    pattern: 'isolation',
    loadType: 'weighted',
    aliases: ['颈后三头臂屈伸', '哑铃颈后三头托举', '颈后臂屈伸', 'overhead triceps extension'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'dips',
    canonicalName: '双杠臂屈伸',
    displayName: '双杠臂屈伸',
    category: 'arms',
    primaryMuscles: ['肱三头肌', '胸大肌'],
    secondaryMuscles: ['三角肌前束'],
    equipment: ['双杠', '自重'],
    pattern: 'horizontal_push',
    loadType: 'bodyweight',
    aliases: ['双杠臂屈伸', '臂屈伸', 'dips'],
    defaultUnit: 'bodyweight',
    requiredFields: ['reps', 'sets'],
  },
  {
    id: 'close_grip_bench_press',
    canonicalName: '窄距卧推',
    displayName: '窄距卧推',
    category: 'arms',
    primaryMuscles: ['肱三头肌'],
    secondaryMuscles: ['胸大肌', '三角肌前束'],
    equipment: ['杠铃'],
    pattern: 'horizontal_push',
    loadType: 'weighted',
    aliases: ['窄距卧推', '窄握卧推', 'close grip bench press'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'ab_wheel',
    canonicalName: '健腹轮',
    displayName: '健腹轮',
    category: 'core',
    primaryMuscles: ['腹直肌', '核心'],
    secondaryMuscles: ['背阔肌', '肩部稳定肌'],
    equipment: ['健腹轮'],
    pattern: 'core_anti_extension',
    loadType: 'bodyweight',
    aliases: ['健腹轮', '腹肌轮', 'ab wheel', 'ab rollout'],
    defaultUnit: 'bodyweight',
    requiredFields: ['reps', 'sets'],
  },
  {
    id: 'crunch',
    canonicalName: '卷腹',
    displayName: '卷腹',
    category: 'core',
    primaryMuscles: ['腹直肌'],
    equipment: ['自重'],
    pattern: 'core_flexion',
    loadType: 'bodyweight',
    aliases: ['仰卧卷腹', '卷腹', 'crunch'],
    defaultUnit: 'bodyweight',
    requiredFields: ['reps', 'sets'],
  },
  {
    id: 'plank',
    canonicalName: '平板支撑',
    displayName: '平板支撑',
    category: 'core',
    primaryMuscles: ['核心'],
    equipment: ['自重'],
    pattern: 'core_anti_extension',
    loadType: 'duration',
    aliases: ['平板支撑', '平板撑', 'plank'],
    defaultUnit: 'min',
    requiredFields: ['duration', 'sets'],
  },
  {
    id: 'hanging_leg_raise',
    canonicalName: '悬垂举腿',
    displayName: '悬垂举腿',
    category: 'core',
    primaryMuscles: ['腹直肌', '髂腰肌'],
    secondaryMuscles: ['握力'],
    equipment: ['单杠'],
    pattern: 'core_flexion',
    loadType: 'bodyweight',
    aliases: ['悬垂举腿', '悬垂抬腿', 'hanging leg raise'],
    defaultUnit: 'bodyweight',
    requiredFields: ['reps', 'sets'],
  },
  {
    id: 'russian_twist',
    canonicalName: '俄罗斯转体',
    displayName: '俄罗斯转体',
    category: 'core',
    primaryMuscles: ['腹斜肌'],
    equipment: ['自重', '药球', '哑铃'],
    pattern: 'core_flexion',
    loadType: 'weighted',
    aliases: ['俄罗斯转体', 'russian twist'],
    defaultUnit: 'kg',
    requiredFields: ['weight', 'reps', 'sets'],
  },
  {
    id: 'treadmill',
    canonicalName: '跑步机',
    displayName: '跑步机',
    category: 'cardio',
    primaryMuscles: ['心肺', '下肢'],
    equipment: ['跑步机'],
    pattern: 'cardio',
    loadType: 'cardio',
    aliases: ['跑步机', '跑步', '慢跑', 'treadmill', 'running'],
    defaultUnit: 'min',
    requiredFields: ['duration'],
    optionalFields: ['distance', 'heartRate', 'calories'],
  },
  {
    id: 'stair_climber',
    canonicalName: '踏步机',
    displayName: '踏步机',
    category: 'cardio',
    primaryMuscles: ['心肺', '臀腿'],
    equipment: ['踏步机'],
    pattern: 'cardio',
    loadType: 'cardio',
    aliases: ['踏步机', '爬楼机', '楼梯机', 'stair climber', 'stairmaster'],
    defaultUnit: 'min',
    requiredFields: ['duration'],
    optionalFields: ['heartRate', 'calories'],
  },
  {
    id: 'elliptical',
    canonicalName: '椭圆机',
    displayName: '椭圆机',
    category: 'cardio',
    primaryMuscles: ['心肺', '下肢'],
    equipment: ['椭圆机'],
    pattern: 'cardio',
    loadType: 'cardio',
    aliases: ['椭圆机', 'elliptical'],
    defaultUnit: 'min',
    requiredFields: ['duration'],
    optionalFields: ['heartRate', 'calories'],
  },
  {
    id: 'stationary_bike',
    canonicalName: '动感单车',
    displayName: '动感单车',
    category: 'cardio',
    primaryMuscles: ['心肺', '下肢'],
    equipment: ['单车'],
    pattern: 'cardio',
    loadType: 'cardio',
    aliases: ['动感单车', '健身车', '单车', 'cycling', 'stationary bike'],
    defaultUnit: 'min',
    requiredFields: ['duration'],
    optionalFields: ['distance', 'heartRate', 'calories'],
  },
  {
    id: 'rowing_machine',
    canonicalName: '划船机',
    displayName: '划船机',
    category: 'cardio',
    primaryMuscles: ['心肺', '背部', '下肢'],
    equipment: ['划船机'],
    pattern: 'cardio',
    loadType: 'cardio',
    aliases: ['划船机', '划船有氧', 'rowing machine', 'erg'],
    defaultUnit: 'min',
    requiredFields: ['duration'],
    optionalFields: ['distance', 'heartRate', 'calories'],
  },
] satisfies ExerciseDefinition[];

export const exerciseLibraryById = Object.fromEntries(exerciseLibrary.map((exercise) => [exercise.id, exercise])) as Record<string, ExerciseDefinition>;

export function getExerciseCategoryCounts() {
  return exerciseLibrary.reduce<Record<ExerciseCategory, number>>(
    (counts, exercise) => ({
      ...counts,
      [exercise.category]: counts[exercise.category] + 1,
    }),
    {
      chest: 0,
      back: 0,
      legs_glutes: 0,
      shoulders: 0,
      arms: 0,
      core: 0,
      cardio: 0,
      full_body: 0,
    },
  );
}
